export default {
    COLLECTION_ADD: "COLLECTION_ADD",
    COLLECTION_EDIT: "COLLECTION_EDIT",
    COLLECTION_REMOVE: "COLLECTION_REMOVE",
    COLLECTION_FAVORITE_ADD: "COLLECTION_FAVORITE_ADD",
    COLLECTION_FAVORITE_REMOVE: "COLLECTION_FAVORITE_REMOVE"
}